baseURL: "https://example.com/"
languageCode: "en-us"
title: "Geoservices"
params:
  symbolIcon: "u\\1F30E"
  ownerName: "Kartoza"
  ownerURL: "https://www.kartoza.com/"
  siteLogo: "img/Circle-icons-stack.svg"
  description: "OpenGIS Stack Geoservices Site"
server:
  headers:
  - for: /**.html
    values:
      Access-Control-Allow-Origin: http://146.185.160.86
